### ISSUE TITLE
error!!!!

### ISSUE THREAD

**Issue by Jinyong-Huang** [cherubicXN/hawp#10]
when i run the train.py.
the error is
from parsing import _C
hawp/parsing/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z13lsencode_cudaRKN2at6TensorEiiiii

**Comment by Jinyong-Huang** [comment]
I chose python=3.6 
the same error _C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z13lsencode_cudaRKN2at6TensorEiiiii

**Comment by cherubicXN** [comment]
Does your device have an Nvidia GPU? If yes, you may need to check your CUDA compability.

**Comment by Jinyong-Huang** [comment]
thanks!!! I tried to run sudo apt install nvidia-cuda-toolkit. the problem is solved.
