### ISSUE TITLE
关于数据标注的问题。

### ISSUE THREAD

**Issue by Jinyong-Huang** [cherubicXN/hawp#11]
你好，请教你一下，我有一个项目，需要对仓库里托盘上包装箱进行计数，需要分割出包装箱之间的缝隙，我想训练自己采集的数据集，请问需要严格按照你提供的train.json来进行标注嘛，或者说有没有什么快速的方法进行标注。

**Comment by cherubicXN** [comment]
For the format of annotations, I think it would be flexible and you can try to modify the code to fit your data.

For the problems of data annotation, you may need to ask the authors of the Wireframe dataset. I did not try to annotate line segments.
