### ISSUE TITLE
Question about the pretrained model

### ISSUE THREAD

**Issue by WEI-Weipeng** [cherubicXN/hawp#15]
Hello, 
Sorry to bother you via this platform. When I was running the quickstart with the pretrained model, there exists some errors related to _C.so files, which is displayed as follow:

`albert@albert-Precision-5820-Tower:~/hawp$ python scripts/predict.py --config-file config-files/hawp.yaml --img figures/example.png
Traceback (most recent call last):
  File "scripts/predict.py", line 6, in <module>
    from parsing.detector import WireframeDetector
  File "/home/albert/hawp/scripts/parsing/detector.py", line 4, in <module>
    from parsing.encoder.hafm import HAFMencoder
  File "/home/albert/hawp/scripts/parsing/encoder/__init__.py", line 1, in <module>
    from .hafm import HAFMencoder
  File "/home/albert/hawp/scripts/parsing/encoder/hafm.py", line 5, in <module>
    from parsing import _C
ImportError: /home/albert/hawp/scripts/parsing/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z13lsencode_cudaRKN2at6TensorEiiiii
`

Could you please indicate how to solve this? Thanks a lot! 

Weipeng

**Comment by cherubicXN** [comment]
Please refer to [this issue](https://github.com/cherubicXN/hawp/issues/14)

**Comment by WEI-Weipeng** [comment]
Thank you very much!
