### ISSUE TITLE
Article and Code Discrepancy for Junction and Line Proposal Matching

### ISSUE THREAD

**Issue by DavidGillsjo** [cherubicXN/hawp#19]
Hi,
Thanks for a great paper and for sharing your code.

According to the article you have a threshold of 10 when matching junctions with line proposals.
In [this code line](https://github.com/cherubicXN/hawp/blob/f1bfafda0601822f9a37074972c0d861cd15ffc4/parsing/detector.py#L153) the requirement is removed. 

Could you please elaborate on that? 
Did you see performance improvement when removing it? Or is it a release bug?

Thanks,
David

**Comment by cherubicXN** [comment]
Hi David,

Yes, there is a discrepancy. In our early study, we used a threshold of 10 pixels in the matching module. Then, I accidentally commented on the use of the threshold in a version, which brings a slightly better performance in the testing phase.  In the training phase, thresholding the matching between junctions and line proposals does not affect the results. We may need to fix this discrepancy in a future version.

Best regards

Nan

**Comment by DavidGillsjo** [comment]
OK, thanks for the explanation!
