### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by alwc** [cherubicXN/hawp#2]
Hi Nan Xue,

Will you be posting the training code this week? Last week from your README it says, "I will finish it in this week". If possible, I would like to reproduce the code sometime this week so that I can play around the model. Much appreciated!

**Comment by cherubicXN** [comment]
Hi, the description of how to train and test our method is updated. You may need to update the cloned source code.

**Comment by alwc** [comment]
@cherubicXN Thanks for the update!

By the way, for the [Wireframe dataset](https://github.com/huangkuns/wireframe) images have .jpg extension, while in your JSON annotation file uses .png extension. Right now I'm using the .png files found in https://github.com/zhou13/lcnn and I'm able to kickstart the training script.

This leads me to wonder, do you have the `wireframe.py` processing script similar to https://github.com/zhou13/lcnn/blob/master/dataset/wireframe.py that creates the JSON annotation file?

**Comment by cherubicXN** [comment]
Yes, it is similar to the script in L-CNN. I will update it.
