### ISSUE TITLE
torch版本问题

### ISSUE THREAD

**Issue by chenluuyou** [cherubicXN/hawp#21]
您好，我发现torch版本高于1.2时会报下列错误
undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

请问一下您的torch版本是多少

**Comment by chenluuyou** [comment]
我的cuda版本也是10.0

**Comment by dongyangcai** [comment]
我这边torch版本使用1.8时结果会变得不准确

**Comment by cherubicXN** [comment]
> 您好，我发现torch版本高于1.2时会报下列错误
> undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
> 
> 请问一下您的torch版本是多少

pytorch 1.4

**Comment by cherubicXN** [comment]
> 我这边torch版本使用1.8时结果会变得不准确

Could you please provide more information about the issue you found?

**Comment by cherubicXN** [comment]
I have checked this issue and fixed the bug https://github.com/cherubicXN/hawp/commit/207df1a1130e0d5fb4e406b862a66344248b5dc9#r55007851

**Comment by cherubicXN** [comment]
> 我这边torch版本使用1.8时结果会变得不准确
Thanks for your comment! @dongyangcai
