### ISSUE TITLE
Need to uncomment a line in setup.py for pip install

### ISSUE THREAD

**Issue by rpautrat** [cherubicXN/hawp#38]
Hi,

Thank you again for the great work and for the latest updates of the HAWP models. This is a great work and is very useful for the community!

I just have a minor question regarding the `setup.py` file. The line https://github.com/cherubicXN/hawp/blob/f18f10e95a685abb1afc2a7b806c275da155a0a0/setup.py#L19 is currently commented out and prevents the package from being installed with pip. Running ```pip install -e .``` results in the following error for me:
```
error: Multiple top-level packages discovered in a flat-layout: ['hawp', 'docker', 'configs', 'weights', 'evaluation'].
      
To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.
[end of output]
  
 note: This error originates from a subprocess, and is likely not a problem with pip.
```

Uncommenting this line fixes the issue and allows the installation with pip. What is the reasoning behind commenting this line out? Would it be possible to uncomment it in the public repo? I can of course fork it and do the change myself, but some people might also benefit from it.

**Comment by cherubicXN** [comment]
Hi, thanks for your feedback!

Because the setup function requires to specify the packages, uncommenting the line will pass the following packages
```
>>> find_packages(exclude=("configs","tests"))
['hawp', 'evaluation', 'hawp.base', 'hawp.encoder', 'hawp.ssl', 'hawp.fsl', 'hawp.base.csrc', 'hawp.base.utils', 'hawp.ssl.config', 'hawp.ssl.misc', 'hawp.ssl.datasets', 'hawp.ssl.models', 'hawp.ssl.datasets.transforms', 'hawp.fsl.dataset', 'hawp.fsl.config', 'hawp.fsl.model', 'hawp.fsl.backbones', 'hawp.fsl.config.models', 'evaluation.sAPEval', 'evaluation.EdgeEval', 'evaluation.RasterizeLine']
```
which include ``hawp`` as a package, thus fixing the issues.
 
I have pushed the changes in this [commit](https://github.com/cherubicXN/hawp/commit/45bd43f704fc6252d88e06ba19d379b7a5753785) to fix this issue. You can try to pull the latest version.

Thanks again!

Nan

**Comment by rpautrat** [comment]
Perfect, thanks a lot Nan!
