### ISSUE TITLE
Questions about the paper and code version

### ISSUE THREAD

**Issue by eleveneee** [cherubicXN/hawp#47]
Thanks for your work! That‘s excellent! I am very interested in your research. When I learned about you, I found that there are several versions of the paper and code. I want to ask about the relationship between them.
Q1：Is《Holistically-Attracted Wireframe Parsing: From Supervised to Self-Supervised Learning》 an improvement of 《Holistically-Attracted Wireframe Parsing》？
Q2：If I want to run the code, which one is better to learn? Is it the latest version?   But I haven't seen the relevant running tutorials in the [new version](https://github.com/cherubicXN/hawp). Do I still need to refer to the [previous code links](https://github.com/bloom1123/hawp)?

**Comment by cherubicXN** [comment]
A1: Yes, it is a journal extension of our conference paper. 
A2: It depends on your requirement. The previous version is tagged as ``0.1`` in my repo, you can also visit it from https://github.com/cherubicXN/hawp/tree/0.1. If you want to use deep models like the traditional LSD without tuning, HAWPv3 would be better. If you need to compare your method with ours in a fully-supervised learning paradigm, both HAWPv1 and HAWPv2 are ok.

**Comment by cherubicXN** [comment]
Because the extended version is a preprint, you can use the old code without considering the updates. Of course, if our updates are useful for you, I will be very happy!

**Comment by eleveneee** [comment]
Thank you very much for your timely reply! Very useful. Good luck!
