### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by www322** [cherubicXN/hawp#5]
Hi, thank you for your work. When I train with your code, I met 'Segmentation fault (core dumped)' error, can you help check the code, thank you!

**Comment by cherubicXN** [comment]
Could you post the training log?

**Comment by www322** [comment]
> Could you post the training log?

just begin...
2020-06-12 11:21:37,967 hawp INFO: Saving config into: outputs/hawp/config.yml
2020-06-12 11:21:55,088 hawp.trainer INFO: No checkpoint found. Initializing model from scratch
Segmentation fault (core dumped)

**Comment by cherubicXN** [comment]
Any more information?

**Comment by www322** [comment]
i fork your project, just change 'png' to 'jpg', no more other changes.

**Comment by cherubicXN** [comment]
What are your hardware devices and the CUDA version?

**Comment by cherubicXN** [comment]
Could you run the data loader without model forward?

**Comment by www322** [comment]
> Could you run the data loader without model forward?

My cuda is 8.0 before, now i change to cuda10.2, now i can run normally. Thank you very much!
