### ISSUE TITLE
what is wireframe-10iters.yaml like, how can I set my dataset?

### ISSUE THREAD

**Issue by bluove** [cherubicXN/hawp#53]
In [docs/HAWPv3.train.md], there is code:
```python
python -m hawp.ssl.homoadp-bm --metarch HAWP-heatmap \
    --datacfg hawp/ssl/config/exports/wireframe-10iters.yaml \
    --workdir exp-ssl/hawpv3-round0 \
    --epoch 10 \
    --modelcfg exp-ssl/hawpv3-round0/model.yaml \
    --min-score 0.75   --batch-size=16
```
but I can't find hawp/ssl/config/exports/wireframe-10iters.yaml, what is this file?

**Comment by cherubicXN** [comment]
Hi @bluove, I have pushed the related files in [this directory](https://github.com/cherubicXN/hawp/blob/main/hawp/ssl/config/exports/)
