### ISSUE TITLE
the new pth

### ISSUE THREAD

**Issue by pipigenius** [cherubicXN/hawp#54]
Great work.
Is hawpv3-ce3ae2cb.pth not available right now? 
Thank you

**Comment by cherubicXN** [comment]
Hi, thanks for your kind words. 
The new checkpoint ``hawpv3-ce3ae2cb.pth`` was uploaded last week at [https://github.com/cherubicXN/hawp-torchhub/releases/tag/HAWPv3](thisurl)

**Comment by pipigenius** [comment]
I replaced hawpv3-fdc5487a.pth with the hawpv3-ce3ae2cb.pth, but there is something wrong with _state_dict_.

**Comment by cherubicXN** [comment]
Hi @pipigenius, you may need to update the code in the first, and specify the argument --metarch as ``HAWP-hrheat``. Below is an example
```
python -m hawp.ssl.predict --metarch HAWP-hrheat --cfg hawp/ssl/config/hawpv3-hrheat.yaml  --ckpt checkpoints/hawpv3-ce3ae2cb.pth --img ~/images/*.JPG -t=0.05
```

**Comment by pipigenius** [comment]
Fantastic, it performs better!
Thank you Xue Nan :)
